#!/bin/bash
# Create an API token in the database and store it in a file

curdir="$(dirname "$(readlink -f "$0")")"
if [ -f "${curdir}/lava-credentials.txt" ]; then
  . "${curdir}"/lava-credentials.txt
fi

lavaurl=http://localhost
tools_path="${tools_path:-/home/lava/bin}"

#obtain the csrf token
data=$(curl -s -c ${tools_path}/cookies.txt $lavaurl/accounts/login/)

#login
csrf="csrfmiddlewaretoken="$(grep csrftoken ${tools_path}/cookies.txt | cut -d$'\t' -f 7)
login=$csrf\&username=$adminuser\&password=$adminpass
curl -b ${tools_path}/cookies.txt -c ${tools_path}/cookies.txt -d $login -X POST $lavaurl/admin/login/

#create an api key
csrf="csrfmiddlewaretoken="$(grep csrftoken ${tools_path}/cookies.txt | cut -d$'\t' -f 7)
createapi=$csrf\&description=autogenerated
curl -b ${tools_path}/cookies.txt -c ${tools_path}/cookies.txt -d $createapi -X POST $lavaurl/api/tokens/create/

#retrieve the api key and store it in a file
curl -b ${tools_path}/cookies.txt http://localhost/admin/linaro_django_xmlrpc/authtoken/1/ | grep id_secret | sed -n 's/.*value="\([^"]*\).*/\1/p' > ${tools_path}/apikey.txt

echo -e "\n\n#####################################\n"
echo -e "# LAVA ADMIN USER = $adminuser"
echo -e "# LAVA ADMIN PASSWD = $adminpass"
echo -e "# LAVA SLAVE HOSTNAME =$(cat ${tools_path}/hostname.txt)"
echo -n "# LAVA APIKEY =$(cat ${tools_path}/apikey.txt)"
echo -e "\n\n#####################################\n"
