#!/bin/bash
# Create an API token in the database and store it in a file

adminuser=admin
adminpass=admin

lavaurl=http://localhost

#obtain the csrf token
data=$(curl -s -c cookies.txt $lavaurl/accounts/login/)

#login
csrf="csrfmiddlewaretoken="$(grep csrftoken cookies.txt | cut -d$'\t' -f 7)
login=$csrf\&username=$adminuser\&password=$adminpass
curl -b cookies.txt -c cookies.txt -d $login -X POST $lavaurl/admin/login/

#create an api key
csrf="csrfmiddlewaretoken="$(grep csrftoken cookies.txt | cut -d$'\t' -f 7)
createapi=$csrf\&description=autogenerated
curl -b cookies.txt -c cookies.txt -d $createapi -X POST $lavaurl/api/tokens/create/

#retrieve the api key and store it in a file
curl -b cookies.txt http://localhost/admin/linaro_django_xmlrpc/authtoken/1/ | grep id_secret | sed -n 's/.*value="\([^"]*\).*/\1/p' > apikey.txt 

echo -e "\n\n#####################################\n"
echo -e "# LAVA ADMIN USER = $adminuser"
echo -e "# LAVA ADMIN PASSWD = $adminpass"
echo -e "# LAVA SLAVE HOSTNAME =$(cat /hostname)"
echo -n "# LAVA APIKEY =$(cat apikey.txt)"
echo -e "\n\n#####################################\n"
